version: "2"
run:
  concurrency: 4
linters:
  enable:
    - depguard
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - godot
    - gosec
    - misspell
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - tparallel
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/zostay
            - gopkg.in/yaml.v3
            - github.com/spf13/cobra
            - github.com/xeipuuv/gojsonschema
            - github.com/pelletier/go-toml/v2
        tests:
          files:
            - $test
          allow:
            - $gostd
            - github.com/zostay
            - gopkg.in/yaml.v3
            - github.com/xeipuuv/gojsonschema
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
