site_name: Genifest
site_description: Kubernetes manifest generation tool for GitOps workflows
site_author: Qubling LLC
site_url: https://genifest.qubling.com

# Repository
repo_name: zostay/genifest
repo_url: https://github.com/zostay/genifest
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2025 Qubling LLC

# Documentation directory
docs_dir: docs

# Exclude files
exclude_docs: |
  includes/
  README.md

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  
  # Colors
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Logo and favicon
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  
  # Language
  language: en

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      enabled: false
  - git-committers:
      repository: zostay/genifest
      branch: master
      enabled: false

# Customization
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zostay/genifest
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/qubling/genifest
#  analytics:
#    provider: google
#    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: zostay
      repo: genifest
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Core Concepts: user-guide/concepts.md
    - CLI Reference: user-guide/cli-reference.md
    - Configuration Files: user-guide/configuration.md
    - Value Generation: user-guide/value-generation.md
    - Tag Filtering: user-guide/tag-filtering.md
  - Examples:
    - Guestbook Tutorial: examples/guestbook.md
    - Common Patterns: examples/patterns.md
    - GitOps Workflows: examples/gitops.md
  - Reference:
    - Configuration Schema: reference/schema.md
    - ValueFrom Types: reference/valuefrom.md
    - Functions: reference/functions.md
    - Troubleshooting: reference/troubleshooting.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Release Process: development/releases.md
  - Changelog: changelog.md

# Additional configuration
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js