apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-config
  namespace: guestbook
  labels:
    app: guestbook
    component: config
  annotations:
    genifest.qubling.com/rotN: "13"
data:
  api-url: "http://guestbook-backend-service/api"
  database-host: "postgres-service"
  database-port: "5432"
  database-name: "guestbook"
  max-entries: "100"
  pagination-size: "10"
  cors-origin: "https://guestbook.example.com"
  app.yaml: "app:\n  name: \"Guestbook Application\"\n  version: \"1.0.0\"\n  description: \"A simple guestbook application with React frontend and Node.js backend\"\n\nserver:\n  port: 8080\n  host: \"0.0.0.0\"\n  cors:\n    origin: \n      - \"https://guestbook.example.com\"\n      - \"http://localhost:3000\"\n    credentials: true\n  rateLimit:\n    windowMs: 900000  # 15 minutes\n    max: 100          # limit each IP to 100 requests per windowMs\n\ndatabase:\n  host: \"${DATABASE_HOST}\"\n  port: \"${DATABASE_PORT}\"\n  name: \"${DATABASE_NAME}\"\n  user: \"${DATABASE_USER}\"\n  password: \"${DATABASE_PASSWORD}\"\n  ssl: false\n  pool:\n    min: 2\n    max: 10\n    idle: 10000\n\nauth:\n  jwt:\n    secret: \"${JWT_SECRET}\"\n    expiresIn: \"24h\"\n  session:\n    secret: \"${SESSION_SECRET}\"\n    maxAge: 86400000  # 24 hours\n\nfeatures:\n  maxEntries: 100\n  enableModeration: true\n  allowAnonymous: true\n  pagination:\n    defaultPageSize: 10\n    maxPageSize: 50\n\nlogging:\n  level: \"info\"\n  format: \"json\"\n  includeRequest: true\n  excludePaths:\n    - \"/health\"\n    - \"/metrics\"\n\nmonitoring:\n  healthCheck:\n    enabled: true\n    path: \"/health\"\n  metrics:\n    enabled: true\n    path: \"/metrics\"\n\nfrontend:\n  title: \"Welcome to our Guestbook\"\n  subtitle: \"Share your thoughts with us!\"\n  theme:\n    primaryColor: \"#3B82F6\"\n    secondaryColor: \"#10B981\"\n    backgroundColor: \"#F9FAFB\"\n  features:\n    darkMode: true\n    autoRefresh: true\n    refreshInterval: 30000  # 30 seconds"
  quote: "Bs nyy glenaavrf, n glenaal fvapreryl rkrepvfrq sbe gur tbbq bs vgf ivpgvzf znl or gur zbfg bccerffvir."
