files:
  - backend-deployment.yaml
  - backend-service.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - secret.yaml

changes:
  - tag: "production"
    fileSelector: "*-deployment.yaml"
    keySelector: ".spec.replicas"
    valueFrom:
      call:
        function: "get-replicas"
        args:
          - name: "environment"
            valueFrom:
              default:
                value: "production"

  - tag: "staging"
    fileSelector: "*-deployment.yaml"
    keySelector: ".spec.replicas"
    valueFrom:
      call:
        function: "get-replicas"
        args:
          - name: "environment"
            valueFrom:
              default:
                value: "staging"
  - fileSelector: "*-deployment.yaml"
    keySelector: ".spec.template.spec.containers[0].image"
    valueFrom:
      call:
        function: "get-image-tag"
        args:
          - name: "service"
            valueFrom:
              default:
                value: "guestbook-frontend"
          - name: "environment"
            valueFrom:
              default:
                value: "dev"
