apiVersion: v1
kind: Secret
metadata:
  name: guestbook-secrets
  namespace: guestbook
  labels:
    app: guestbook
    component: secrets
type: Opaque
data:
  database-user: Z3Vlc3Rib29r
  database-password: cGFzc3dvcmQxMjM=
  jwt-secret: c3VwZXJzZWNyZXRqd3RrZXl0aGF0c2hvdWxkYmVyYW5kb20=