apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: guestbook
  labels:
    app: postgres
    component: secrets
type: Opaque
data:
  database-user: Z3Vlc3Rib29r
  database-password: cGFzc3dvcmQxMjM=