apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: guestbook
  labels:
    app: postgres
    component: database
    tier: data
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres